.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH GODEX 1 "2015-07-24"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
godex \- dumps exported information of packages or selected package objects
.SH SYNOPSIS
.B godex
.RI [ flags ]
.RI {
.IR path[.name]
.RI }
.SH DESCRIPTION
The godex command prints (dumps) exported information of packages or selected
package objects.

In contrast to godoc, godex extracts this information from compiled object
files. Hence the exported data is truly what a compiler will see, at the cost
of missing commentary.

.SH OPTIONS

Run godex \-help for more details.

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
