.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH GOIMPORTS 1 "2015-07-24"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
goimports \- updates your Go import lines
.SH SYNOPSIS
.B goimports
.RI [ flags ]
.RI [
.IR "path ..."
.RI ]
.SH DESCRIPTION
Command goimports updates your Go import lines, adding missing ones and
removing unreferenced ones.

.SH OPTIONS

Run goimports \-help for more details.

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
