.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH GOLANG-EG 1 "2015-07-24"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
golang-eg \- performs example-based refactoring
.SH SYNOPSIS
.B golang-eg
.SH DESCRIPTION
The golang-eg command performs example-based refactoring.

Run golang-eg \-help for more details.

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
