.\"                                      Hey, EMACS: -*- nroff -*-
.de Vb \" Begin verbatim text
.ft CW
.nf
.ne \\$1
..
.de Ve \" End verbatim text
.ft R
.fi
..
.TH HTML2ARTICLE 1 "2013-12-02"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
html2article \- converts an HTML file to an article in present format
.SH SYNOPSIS
.B html2article
.SH DESCRIPTION

This program takes an HTML file and outputs a corresponding article file in
present format. See: code.google.com/p/go.tools/present

.SH AUTHOR
.PP
This manual page was written by Michael Stapelberg <stapelberg@debian.org>,
for the Debian project (and may be used by others).
